### ISSUE TITLE
players names arent colored

### ISSUE THREAD

**Issue by btramsyeehaw** [bartekpacia/mlb-thing#4]
![image](https://user-images.githubusercontent.com/51712687/59612298-24439a00-911d-11e9-829b-bc12e608ec7b.png)

on the image above Brock Holt, Blake Swihart, Sam Travis should be colored yellow as they are on the bench. It would **be cool (not necessary for my enjoyment)** if players _in "bullpen"_ (Barnes, Brasier, Eovaldi, Porcello, Price, Rodriguez, Workman) were also colored.

**Comment by bartekpacia** [comment]
i think i fixed it
